version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: yana-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - "~/.gradle"
            - "~/.gradle/caches/modules-2"
            - "~/.m2"
          key: yana-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Run Tests
          command: ./gradlew test -Pminify=true
      - run:
          name: Assemble all variants
          command: ./gradlew assemble -Pminify=true
      - store_artifacts:
                path: app/build/outputs
                destination: outputs



